-- MySQL Script generated by MySQL Workbench
-- lun 14 feb 2022 18:03:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema red_social
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema red_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `red_social` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `red_social` ;

-- -----------------------------------------------------
-- Table `red_social`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `red_social`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `fecha_cumpleanio` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `red_social`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `red_social`.`publicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `contenido` TEXT NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicaciones_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_publicaciones_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `red_social`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `red_social`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `red_social`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` VARCHAR(45) NOT NULL,
  `publicacion_id` VARCHAR(45) NOT NULL,
  `texto` TEXT NOT NULL,
  `fecha` TIMESTAMP NOT NULL,
  `usuarios_id` INT NOT NULL,
  `publicaciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_usuarios_idx` (`usuarios_id` ASC),
  INDEX `fk_comentarios_publicaciones1_idx` (`publicaciones_id` ASC),
  CONSTRAINT `fk_comentarios_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `red_social`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicaciones_id`)
    REFERENCES `red_social`.`publicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
